/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.flostajprojesi;

/**
 *
 * @author tuba
 */
public class RaporlamaEkrani extends javax.swing.JFrame {

    /**
     * Creates new form RaporlamaEkrani
     */
    public RaporlamaEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TumStokRaporu = new javax.swing.JComboBox<>();
        StokUyarısı = new javax.swing.JComboBox<>();
        EnCokSatilanUrunler = new javax.swing.JComboBox<>();
        RaporOlustur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        TumStokRaporu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TumStokRaporu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TumStokRaporuActionPerformed(evt);
            }
        });

        StokUyarısı.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        EnCokSatilanUrunler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RaporOlustur.setText("Rapor Oluştur");
        RaporOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaporOlusturActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TumStokRaporu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(StokUyarısı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(EnCokSatilanUrunler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(RaporOlustur))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TumStokRaporu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StokUyarısı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnCokSatilanUrunler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RaporOlustur))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tabloyuDoldur(List<Urun> urunListesi) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Tabloyu temizle

    // Sütun başlıklarını kontrol et (Gerekiyorsa ekle)
    if (model.getColumnCount() == 0) {
        model.addColumn("ID");
        model.addColumn("Ürün Adı");
        model.addColumn("Fiyat");
        model.addColumn("Stok");
        model.addColumn("Kategori");
    }

    // Listeden gelen verileri tabloya ekle
    for (Urun urun : urunListesi) {
        Object[] row = {
            urun.getUrunId(),
            urun.getUrunAdi(),
            urun.getFiyat(),
            urun.getStok(),
            urun.getKategori()
        };
        model.addRow(row);
    }
}

private void hataGoster(String mesaj) {
    JOptionPane.showMessageDialog(this, mesaj, "Hata", JOptionPane.ERROR_MESSAGE);
}

    private void TumStokRaporuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TumStokRaporuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TumStokRaporuActionPerformed

    private void RaporOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaporOlusturActionPerformed
        try {
        // Rapor türünü JComboBox'tan al
        String seciliRapor = cmbRaporTuru.getSelectedItem().toString(); 
        UrunService urunService = new UrunService();
        List<Urun> raporSonuclari = null;

        if (seciliRapor.equals("Tüm Stok Raporu")) {
            // Tüm ürünleri çek
            raporSonuclari = urunService.tumUrunleriGetir();
            
        } else if (seciliRapor.equals("Stok Uyarısı (Az Kalanlar)")) {
            // Az stoklu ürünleri çekecek yeni bir metot çağırılacak
            raporSonuclari = urunService.dusukStokluUrunleriGetir(); 
            
        } else {
            // Hiçbir rapor seçilmediyse
            hataGoster("Lütfen bir rapor türü seçin.");
            return; 
        }

        // Sonuçları tabloya doldur
        if (raporSonuclari != null) {
            tabloyuDoldur(raporSonuclari);
        }
        
    } catch (Exception e) {
        hataGoster("Rapor oluşturulurken bir hata oluştu: " + e.getMessage());
    }
    }//GEN-LAST:event_RaporOlusturActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RaporlamaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RaporlamaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RaporlamaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RaporlamaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RaporlamaEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EnCokSatilanUrunler;
    private javax.swing.JButton RaporOlustur;
    private javax.swing.JComboBox<String> StokUyarısı;
    private javax.swing.JComboBox<String> TumStokRaporu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
