/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.flostajprojesi;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuba
 */
public class UrunIslemleri extends javax.swing.JFrame {

    /**
     * Creates new form UrunIslemleri
     */
    public UrunIslemleri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUrunAdi = new javax.swing.JTextField();
        txtFiyat = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        txtKategori = new javax.swing.JTextField();
        btnEkle = new javax.swing.JButton();
        btnGuncelle = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        btnListele = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ürün Adı:");

        jLabel2.setText("Fiyat: ");

        jLabel3.setText("Stok:");

        jLabel4.setText("Kategori:");

        txtUrunAdi.setText("jTextField1");

        txtFiyat.setText("jTextField2");

        txtStok.setText("jTextField3");
        txtStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokActionPerformed(evt);
            }
        });

        txtKategori.setText("jTextField4");

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        btnGuncelle.setText("Güncelle");
        btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelleActionPerformed(evt);
            }
        });

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        btnListele.setText("Listele");
        btnListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeleActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable2);

        jScrollPane4.setViewportView(jScrollPane6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(67, 67, 67)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(597, 597, 597))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(67, 67, 67)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEkle)
                        .addGap(94, 94, 94)
                        .addComponent(btnGuncelle)
                        .addGap(88, 88, 88)
                        .addComponent(btnSil)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(348, 348, 348)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnListele))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEkle)
                            .addComponent(btnGuncelle)
                            .addComponent(btnSil)
                            .addComponent(btnListele))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        try {
        // Kullanıcı arayüzünden verileri al
        String urunAdi = txtUrunAdi.getText();
        double fiyat = Double.parseDouble(txtFiyat.getText());
        int stok = Integer.parseInt(txtStok.getText());
        String kategori = txtKategori.getText();

        // Yeni bir Urun nesnesi oluştur
        Urun yeniUrun = new Urun();
        yeniUrun.setUrunAdi(urunAdi);
        yeniUrun.setFiyat(fiyat);
        yeniUrun.setStok(stok);
        yeniUrun.setKategori(kategori);

        // UrunService üzerinden ürünü veritabanına kaydet
        UrunService urunService = new UrunService();
        urunService.urunEkle(yeniUrun);

        // Başarılı mesajı göster ve tabloyu yenile
        JOptionPane.showMessageDialog(this, "Ürün başarıyla eklendi!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
        
        // Tabloyu yenilemek için listeleme metodunu çağır
        btnListeleActionPerformed(null);
        
    } catch (NumberFormatException ex) {
        // Sayısal alanlara harf girilirse hata mesajı göster
        JOptionPane.showMessageDialog(this, "Fiyat ve stok alanlarına geçerli sayılar giriniz.", "Hata", JOptionPane.ERROR_MESSAGE);
    } catch (HeadlessException ex) {
        // Diğer olası hatalar için genel hata mesajı
        JOptionPane.showMessageDialog(this, "Ürün eklenirken bir hata oluştu: " + ex.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeleActionPerformed
try {
        // UrunService nesnesi oluştur
        UrunService urunService = new UrunService();
        // Tüm ürünleri veritabanından al
        List<Urun> urunListesi = urunService.tumUrunleriGetir();

        // JTable için model oluştur
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        // Tabloyu temizle
        model.setRowCount(0);

        // Tabloya sütun isimlerini ekle (eğer daha önce eklenmediyse)
        if (model.getColumnCount() == 0) {
            model.addColumn("ID");
            model.addColumn("Ürün Adı");
            model.addColumn("Fiyat");
            model.addColumn("Stok");
            model.addColumn("Kategori");
        }

        // Ürün listesini tabloya ekle
        for (Urun urun : urunListesi) {
            Object[] row = {
                urun.getUrunId(),
                urun.getUrunAdi(),
                urun.getFiyat(),
                urun.getStok(),
                urun.getKategori()
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        // Hata durumunda kullanıcıya bilgi ver
        JOptionPane.showMessageDialog(this, "Ürünler listelenirken bir hata oluştu: " + e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
    }    }//GEN-LAST:event_btnListeleActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // Tabloda seçili olan satırın indeksini al
    int selectedRow = jTable1.getSelectedRow();
    
    // Eğer bir satır seçilmişse
    if (selectedRow != -1) {
        // Seçili satırdaki verileri al
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int urunId = (int) model.getValueAt(selectedRow, 0);
        String urunAdi = model.getValueAt(selectedRow, 1).toString();
        double fiyat = (double) model.getValueAt(selectedRow, 2);
        int stok = (int) model.getValueAt(selectedRow, 3);
        String kategori = model.getValueAt(selectedRow, 4).toString();

        // Alınan verileri JTextField'lara yerleştir
        txtUrunId.setText(String.valueOf(urunId));
        txtUrunAdi.setText(urunAdi);
        txtFiyat.setText(String.valueOf(fiyat));
        txtStok.setText(String.valueOf(stok));
        txtKategori.setText(kategori);
    }
    }//GEN-LAST:event_jTable2MouseClicked

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
         // Tabloda seçili olan satırın indeksini al
    int selectedRow = jTable1.getSelectedRow();
    
    // Eğer bir satır seçilmişse
    if (selectedRow != -1) {
        int dialogResult = JOptionPane.showConfirmDialog(this, "Seçili ürünü silmek istediğinize emin misiniz?", "Onay", JOptionPane.YES_NO_OPTION);
        
        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                // Seçili satırdaki ürün ID'sini al
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                int urunId = (int) model.getValueAt(selectedRow, 0);

                // UrunService üzerinden ürünü sil
                UrunService urunService = new UrunService();
                urunService.urunSil(urunId);

                // Başarılı mesajı göster ve tabloyu yenile
                JOptionPane.showMessageDialog(this, "Ürün başarıyla silindi!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
                
                // Tabloyu yenilemek için listeleme metodunu çağır
                btnListeleActionPerformed(null);
                
            } catch (HeadlessException ex) {
                JOptionPane.showMessageDialog(this, "Ürün silinirken bir hata oluştu: " + ex.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Lütfen silmek için bir ürün seçin.", "Uyarı", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed
        try {
        int urunId = Integer.parseInt(txtUrunId.getText());
        String urunAdi = txtUrunAdi.getText();
        double fiyat = Double.parseDouble(txtFiyat.getText());
        int stok = Integer.parseInt(txtStok.getText());
        String kategori = txtKategori.getText();

        Urun guncelUrun = new Urun();
        guncelUrun.setUrunId(urunId);
        guncelUrun.setUrunAdi(urunAdi);
        guncelUrun.setFiyat(fiyat);
        guncelUrun.setStok(stok);
        guncelUrun.setKategori(kategori);

        UrunService urunService = new UrunService();
        urunService.urunGuncelle(guncelUrun);

        JOptionPane.showMessageDialog(this, "Ürün başarıyla güncellendi!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
        
        btnListeleActionPerformed(null);
        
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "ID, Fiyat ve stok alanlarına geçerli sayılar giriniz.", "Hata", JOptionPane.ERROR_MESSAGE);
    } catch (HeadlessException ex) {
        JOptionPane.showMessageDialog(this, "Ürün güncellenirken bir hata oluştu: " + ex.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuncelleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrunIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrunIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrunIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrunIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UrunIslemleri().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnListele;
    private javax.swing.JButton btnSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtFiyat;
    private javax.swing.JTextField txtKategori;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtUrunAdi;
    // End of variables declaration//GEN-END:variables

    private static class txtUrunId {

        private static void setText(String valueOf) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public txtUrunId() {
        }
    }
}
