/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tuba
 */
public class AnaEkran extends javax.swing.JFrame {

    /**
     * Creates new form AnaEkran
     */
    public AnaEkran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUrunIslemleri = new javax.swing.JButton();
        btnStokTakip = new javax.swing.JButton();
        btnRaporlama = new javax.swing.JButton();
        btnCikis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUrunIslemleri.setText("Ürün İşlemleri");
        btnUrunIslemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrunIslemleriActionPerformed(evt);
            }
        });

        btnStokTakip.setText("Stok Takip");
        btnStokTakip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStokTakipActionPerformed(evt);
            }
        });

        btnRaporlama.setText("Raporlama");
        btnRaporlama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaporlamaActionPerformed(evt);
            }
        });

        btnCikis.setText("Çıkış");
        btnCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUrunIslemleri)
                    .addComponent(btnStokTakip)
                    .addComponent(btnRaporlama)
                    .addComponent(btnCikis))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUrunIslemleri)
                .addGap(30, 30, 30)
                .addComponent(btnStokTakip)
                .addGap(31, 31, 31)
                .addComponent(btnRaporlama)
                .addGap(31, 31, 31)
                .addComponent(btnCikis)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnStokTakip(java.awt.event.ActionEvent evt) {
        btnStokTakip.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Stok Takip butonuna tıklandı.");
        // Buraya stok durumunu gösteren tablo veya grafik eklenebilir
    }
});
    }
    private void btnRaporlama(java.awt.event.ActionEvent evt) {
        btnRaporlama.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Raporlama butonuna tıklandı.");
        // Buraya satış raporu, stok raporu gibi PDF/Excel çıktıları alınabilir
    }
});

    }
    private void btnCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisActionPerformed
    btnCikis.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Çıkış butonuna tıklandı.");
        System.exit(0);
    }
});    }//GEN-LAST:event_btnCikisActionPerformed

    private void btnUrunIslemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrunIslemleriActionPerformed
    btnUrunIslemleri.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Ürün İşlemleri butonuna tıklandı.");
        // Buraya ürün ekleme, silme veya güncelleme ekranı açılabilir
    }
});    }//GEN-LAST:event_btnUrunIslemleriActionPerformed

    private void btnStokTakipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokTakipActionPerformed
         // Stok Takip ekranını aç
    StokTakip stokEkrani = new StokTakip();
    stokEkrani.setVisible(true);
    // Ana ekranı gizle
    this.dispose();
    }//GEN-LAST:event_btnStokTakipActionPerformed

    private void btnRaporlamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaporlamaActionPerformed
    RaporlamaEkrani raporEkrani = new RaporlamaEkrani();
    raporEkrani.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnRaporlamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCikis;
    private javax.swing.JButton btnRaporlama;
    private javax.swing.JButton btnStokTakip;
    private javax.swing.JButton btnUrunIslemleri;
    // End of variables declaration//GEN-END:variables
}
